#!/bin/bash
# Fills the specified menu database with any missing entries
# from any PATH directory
menu="main"
if [[ -n $1 ]]; then
	menu=$1
fi
if [[ ! -e "${HOME}/.menu/${menu}.sqlite" ]]; then
	echo "No menu file found. Create new one."
	mkdir -pv "${HOME}/.menu/"
	sqlite3 "${HOME}/.menu/${menu}.sqlite" < ~/.menu/menu.sql
fi

commands_to_be_added()  {
	existing=$(sqlite3 -line "${HOME}/.menu/${menu}.sqlite" "SELECT name FROM commands ORDER BY weight DESC" | grep -v "^$" | cut -b 9- | sort)
	IFS=':'
	(for dir in $PATH; do
		ls -1 "$dir"
	done) | sort -u | comm -13 <(echo "$existing") -
}

IFS=$'\n'
ctba=$(commands_to_be_added)
for c in $(echo "$ctba"); do
	echo "$c|$c|0"
done | sqlite3 -separator "|" "${HOME}/.menu/${menu}.sqlite" ".import /dev/stdin commands"
if [[ -z $ctba ]]; then
	echo "dynmenu: no commands added"
else
	echo "dynmenu: $(echo "$ctba" | wc -l) commands added"
fi
