#!/bin/sh

menu="main"
if [[ -n $1 ]]; then
	menu=$1
fi

shift 1

if [ -e ~/.menu/${menu}.menu ]; then
	cmd=`~/.menu/${menu}.menu $2 | dmenu -i`
elif [ -e ~/.menu/${menu}.sqlite ]; then
	cmd=`sqlite3 -line ~/.menu/${menu}.sqlite "SELECT name FROM commands ORDER BY weight DESC" | grep -v "^$" | cut -b 9- | dmenu -i $@`
else
	echo "menu file not found"
	exit
fi

if [[ "$cmd" == *\; ]]; then
	prefix="urxvt -e "
	cmd="${cmd%\;}"
elif [[ "$cmd" == *\! ]]; then
	prefix="gksu "
	cmd="${cmd%!}"
elif [[ "$cmd" == *\? ]]; then
	prefix="m "
	cmd="${cmd%?}"
fi

if [ -e ~/.menu/${menu}.post ]; then
	cmd=`echo $cmd | ~/.menu/${menu}.post $2`
fi

if [[ "$cmd" == *\; ]]; then
	prefix="urxvt -e "
	cmd="${cmd%\;}"
elif [[ "$cmd" == *\! ]]; then
	prefix="gksu "
	cmd="${cmd%!}"
elif [[ "$cmd" == *\? ]]; then
	prefix="m "
	cmd="${cmd%?}"
fi

$SHELL -c "$prefix$cmd"
