#!/bin/bash

menu_name=$1
shift 1

if [ -e ~/.menu/${menu_name}.menu ]; then
	cmd=`~/.menu/${menu_name}.menu $2 | dmenu -i`
elif [ -e ~/.menu/${menu_name}.sqlite ]; then
	cmd=`sqlite3 -line ~/.menu/${menu_name}.sqlite "SELECT name FROM commands ORDER BY weight DESC" | grep -v "^$" | cut -b 9- | dmenu -i $@`
else
	echo "menu file not found"
	exit
fi

if [[ "$cmd" == *\; ]]; then
	prefix="urxvt -e "
	cmd="${cmd%\;}"
elif [[ "$cmd" == *\! ]]; then
	prefix="gksu "
	cmd="${cmd%!}"
elif [[ "$cmd" == *\? ]]; then
	prefix="m "
	cmd="${cmd%?}"
fi

if [ -e ~/.menu/${menu_name}.post ]; then
	cmd=`echo $cmd | ~/.menu/${menu_name}.post $2`
fi

if [[ "$cmd" == *\; ]]; then
	prefix="urxvt -e "
	cmd="${cmd%\;}"
elif [[ "$cmd" == *\! ]]; then
	prefix="gksu "
	cmd="${cmd%!}"
elif [[ "$cmd" == *\? ]]; then
	prefix="m "
	cmd="${cmd%?}"
fi

$SHELL -c "$prefix$cmd"
